In [56]:
v1 = int(input())
v2 = int(input())
v3 = int(input())

print(f'Tabuada do {v1} de {v2} até {v3}')

if 1<=v1<=99 and 1<=v2<=999 and 1<=v3<=999 :
  for v in range(v2, v3+1):
    print(f'{v1} x {v} = {v1*v}')

9
5
6
Tabuada do 9 de 5 até 6
9 x 5 = 45
9 x 6 = 54